import { IconType } from 'react-icons'
import {
  FaEarListen,
  FaComments,
  FaPoo,
  FaBolt,
  FaHammer,
  FaYinYang,
  FaEye,
  FaBinoculars,
  FaRegClock,
  FaChessKing,
  FaLightbulb,
  FaHandshake,
  FaExpand,
  FaRegFaceGrinWide,
  FaScrewdriverWrench,
  FaBullseye,
  FaShuffle,
  FaHeart,
  FaRocket,
  FaMagnifyingGlass,
  FaFeather,
  FaCommentDots,
  FaHourglassHalf,
  FaCircleQuestion,
  FaGlobe,
} from 'react-icons/fa6'

export const iconMap: { [key: string]: IconType } = {
  ear: FaEarListen,
  comments: FaComments,
  poo: FaPoo,
  bolt: FaBolt,
  hammer: FaHammer,
  yinYang: FaYinYang,
  eye: FaEye,
  binoculars: FaBinoculars,
  clock: FaRegClock,
  chess: FaChessKing,
  lightbulb: FaLightbulb,
  handshake: FaHandshake,
  expand: FaExpand,
  grin: FaRegFaceGrinWide,
  tools: FaScrewdriverWrench,
  bullseye: FaBullseye,
  shuffle: FaShuffle,
  heart: FaHeart,
  rocket: FaRocket,
  magnifyingGlass: FaMagnifyingGlass,
  feather: FaFeather,
  commentsAlt: FaCommentDots,
  hourglass: FaHourglassHalf,
  question: FaCircleQuestion,
  default: FaGlobe,
}